### ISSUE TITLE
Tutorial Mejorar Conexión Ubitiqui

### ISSUE THREAD

**Issue by ConsolaViejuna** [ConsolaViejuna/mkdocs-homeAssistantFacil#3]
Truco para mejoras la conexión con Ubitiqui: https://t.me/DomoticaFacilHomeAssistant/164471

**Comment by javilopezalarcon** [comment]
Mejorar la red wifi que usamos nosotros, no en la que usamos para la domotica, para esa no seria necesario estos ajustes.
Siempre que sea posible, aumentar el ancho del canal de la red 5g a 80mhz, si perdieras cobertura en zonas lejanas, te tocaria bajarlo, ya que cuanto mas ancho, mas datos puede transmitir, pero mas se deteriora la señal con los obstaculos… cada instalacion es diferente y debes probar. 
Lo mejor para elegir el canal del wifi 5g es analizar que hay en tu entorno y siempre que sea posible, elegir el canal mas bajo posible ya que es mas “robusto” aunque aqui, aconsejo encarecidamente que se deje en auto, ya que el propio ap, analizará cual es el mejor a usar en todo momento y si un vecino se planta en tu canal, el cambiará a otro para darte la mejor calidad.
Depende del Access Point (ap de aqui en adelante), se entrará de una manera u otra, esto está echo desde el controlador de ubiquiti, aunque todos los ap suelen tener estas opciones, algunos lo traen activado de casa y otros como en este caso, hay que activarlos.
La que mas se va a beneficiar de estos cambios sera la 5g aprovechando todas las antenas del ap y del dispositivo que uses para conectarte al ap.
Las Opciones a activar serian el UAPSD
(Unscheduled Automatic Power Save Delivery), 
Multicast Enhancement
(Permit devices to send multicast traffic to registered clients at higher data rates.), High Performance Devices
(Connect high performance clients to 5 GHz only) este lo activo ya que en esta red, emito en las 2 bandas, 2.4 y 5g asi obligo a que los dispositivos potentes se conecten a la 5g siempre que sea posible, BSS Transition
(Allow BSS Transition with WNM) y Enable Fast Roaming
(Faster roaming for modern devices with 802.11r compatibility. Older devices may experience connectivity issues)
Aqui si hariamos uso de la solucion propietaria de ubiquiti para el cambio rapido entre ap’s, pero solo si tenemos mas de un ap, si no, es innecesario activarlo 

[Ajustes del wifi ](https://t.me/DomoticaFacilHomeAssistant/165322)

**Comment by javilopezalarcon** [comment]
Para la red de domotica, yo personalmente uso solo una red de 2.4, en ancho de canal al minimo, a 20 (para aumentar cobertura y estabilidad) y en los ajustes, solo activo el UAPSD
(Unscheduled Automatic Power Save Delivery), el BSS Transition
(Allow BSS Transition with WNM) y Enable Fast Roaming
(Faster roaming for modern devices with 802.11r compatibility. Older devices may experience connectivity issues)
Yo no he tenido ningun problema con mis dispositivos, en caso de notar cosas raras, desactivar este ultimo, ya que es una solución propietaria de la marca para que los dispositivos hagan el roaming mucho mas rapido entre ap’s, bajando muchisimo el tiempo de asociación con el nuevo ap, ya que con el, son necesarios muchos menos paquetes de envio para asociarse… al ser la de domotica, son dispositivos que estan quietos, asi que el roaming, no deberian ni usarlo, ya que si la cobertura es buena, no seria necesario esa mejora, asi que si quereis este ultimo no es necesario, pero ahi esta por si quereis probar.

**Comment by javilopezalarcon** [comment]
Como apunte “personal” he visto que en los nuevos controladores de ubiquiti aparece una opcion que seria `enable meshing’ esto es una apreciacion personal, ya que no he podido probarlo ya que tengo una version antigua del controlador. Pero que es una red Mesh? una red mallada, significa que hay varios caminos para llegar al router, los ap entre ellos crean una red para en caso de que un ap caiga, tener otro camino para dar servicio de internet, esa red, la crean por wifi. Esta opcion, Yo, solo la activaria en caso de tener ap’s que reciben solo el internet mediante wifi (a modo de repetidor digamos) para que no coja solo de un ap, si no de varios… en caso de tener los ap’s cableados y llegandoles internet por cable y no por wifi, yo no la habilitaria nunca, porqué? Yo no quiero perder recursos de las antenas wifi de un ap, para asegurarse un enlace por wifi con otro ap, cuando tiene un cable que le da ese internet. Dicho de otro modo, tienes un cable con conexion gigabite al router, para qué quieres que ese ap esté conectado a otro ap por wifi? Estas perdiendo una antena en emision y otra en recepcion para un enlace que nunca deberias de llegar a usar… pero es un apunte personal, que la red Mesh estan de moda, y van muy bien, pero para aps sin cable, asi lo veo yo.

**Comment by javilopezalarcon** [comment]
Por cierto, cosa **SUPER** Importante, para los que tenemos aps de Ubiquiti.
Implementaron la compatibilidad con el nuevo cifrado de WPA3, que es mucho mas seguro que WPA2, problema? Pusieron una opcion, en la que puedes activarlo de manera automatica para si el dispositivo que se conecte es compatible con el nuevo cifrado, lo use y si no, que use WPA2. Problema? De “serie” viene activado en automatico y  No debe de estar muy pulido, con lo que genera desconexiones aleatorias en algunos dispositivos (yo lo he vivido en esp32 por ejemplo) desactivarlo es facil, al menos hasta que esté mas pulido. Entras en configuración, entras en la wifi de la domotica (como minimo, yo lo tengo en las 2 redes que tengo) le das a ADVANCED y bajas en busca de SECURITY y donde pone 

PMF
Protected management frames enhance safety for WiFi connection
Elegimos DISABLE (que apareceria en Optional)

Con eso, a mi se me acabaron los problemas de desconexiones aleatorias, me costó encontrarlo en los foros de ubiquiti oficiales 😅😅
