### ISSUE TITLE
Script comparativo Humedad Exterior e interior

### ISSUE THREAD

**Issue by javilopezalarcon** [ConsolaViejuna/mkdocs-homeAssistantFacil#5]
Si vives en una ciudad costera o con alta humedad, aqui hay un script para comparar la humedad exterior e interior de tu vivienda, para que te aconseje si abrir o no las ventanas de casa para ventilar.

puedo_abrir_las_ventanas:

  sequence:
  - service: tts.google_say
    data:
      entity_id: media_player.salon
      message: '"{% if (states("sensor.humedad_media_casa") | int) < (states("sensor.humedad_exterior_h_matrimonio")
        | int) -%} Yo no abriría. Hay un {{ (states("sensor.humedad_exterior_h_matrimonio")
        | int)-(states("sensor.humedad_media_casa")| int)}} Por ciento mas de Humedad
        en el exterior  {%- elif (states("sensor.humedad_media_casa")  | int) > (states("sensor.humedad_exterior_matrimonio")
        | int) %}    Puedes abrir. Hay un {{ (states("sensor.humedad_media_casa")
        | int) -(states("sensor.humedad_exterior_h_matrimonio") | int) }} Por ciento
        menos de Humedad en el exterior  {%- else -%}  Puedes abrir, pero no tardes
        en cerrar. La humedad ahora en el exterior es similar al interior  {%- endif
        %}"'
  mode: single
  alias: Puedo Abrir las Ventanas
  icon: mdi:window-closed-variant

**Comment by ConsolaViejuna** [comment]
Muchas gracias @javilopezalarcon podías poner el código de la automatización en formato code tipo así:
`Esto es un ejemplo de código`

Más que nada para conservar los espacios y tabuladores
Gracias

**Comment by javilopezalarcon** [comment]
`puedo_abrir_las_ventanas:
  sequence:
  - service: tts.google_say
    data:
      entity_id: media_player.salon
      message: '"{% if (states("sensor.humedad_media_casa") | int) < (states("sensor.humedad_exterior_h_matrimonio")
        | int) -%} Yo no abriría. Hay un {{ (states("sensor.humedad_exterior_h_matrimonio")
        | int)-(states("sensor.humedad_media_casa")| int)}} Por ciento mas de Humedad
        en el exterior  {%- elif (states("sensor.humedad_media_casa")  | int) > (states("sensor.humedad_exterior_matrimonio")
        | int) %}    Puedes abrir. Hay un {{ (states("sensor.humedad_media_casa")
        | int) -(states("sensor.humedad_exterior_h_matrimonio") | int) }} Por ciento
        menos de Humedad en el exterior  {%- else -%}  Puedes abrir, pero no tardes
        en cerrar. La humedad ahora en el exterior es similar al interior  {%- endif
        %}"'
  mode: single
  alias: Puedo Abrir las Ventanas
  icon: mdi:window-closed-variant
`

**Comment by ConsolaViejuna** [comment]
```
puedo_abrir_las_ventanas:
  sequence:
  - service: tts.google_say
    data:
      entity_id: media_player.salon
      message: '"{% if (states("sensor.humedad_media_casa") | int) < (states("sensor.humedad_exterior_h_matrimonio")
        | int) -%} Yo no abriría. Hay un {{ (states("sensor.humedad_exterior_h_matrimonio")
        | int)-(states("sensor.humedad_media_casa")| int)}} Por ciento mas de Humedad
        en el exterior  {%- elif (states("sensor.humedad_media_casa")  | int) > (states("sensor.humedad_exterior_matrimonio")
        | int) %}    Puedes abrir. Hay un {{ (states("sensor.humedad_media_casa")
        | int) -(states("sensor.humedad_exterior_h_matrimonio") | int) }} Por ciento
        menos de Humedad en el exterior  {%- else -%}  Puedes abrir, pero no tardes
        en cerrar. La humedad ahora en el exterior es similar al interior  {%- endif
        %}"'
  mode: single
  alias: Puedo Abrir las Ventanas
  icon: mdi:window-closed-variant
```
